spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/st_order
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:secret124}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 7030

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    register-with-eureka: true
    fetch-registry: true