spring:
  application:
    name: inventory
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/st_inventory
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:secret124}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
server:
  port: 7020
